/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoanofficerRouteImport } from './routes/loanofficer'
import { Route as NewartoflivingRouteImport } from './routes/newartofliving'
import { Route as RealtorRouteImport } from './routes/realtor'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as AuthenticatedAdminListingsRouteImport } from './routes/_authenticated/admin.listings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanofficerRoute = LoanofficerRouteImport.update({
  id: '/loanofficer',
  path: '/loanofficer',
  getParentRoute: () => rootRouteImport,
} as any)
const NewartoflivingRoute = NewartoflivingRouteImport.update({
  id: '/newartofliving',
  path: '/newartofliving',
  getParentRoute: () => rootRouteImport,
} as any)
const RealtorRoute = RealtorRouteImport.update({
  id: '/realtor',
  path: '/realtor',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminListingsRoute =
  AuthenticatedAdminListingsRouteImport.update({
    id: '/admin/listings',
    path: '/admin/listings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/loanofficer': typeof LoanofficerRoute
  '/newartofliving': typeof NewartoflivingRoute
  '/realtor': typeof RealtorRoute
  '/testimonials': typeof TestimonialsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/admin/listings': typeof AuthenticatedAdminListingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/loanofficer': typeof LoanofficerRoute
  '/newartofliving': typeof NewartoflivingRoute
  '/realtor': typeof RealtorRoute
  '/testimonials': typeof TestimonialsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/admin/listings': typeof AuthenticatedAdminListingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/loanofficer': typeof LoanofficerRoute
  '/newartofliving': typeof NewartoflivingRoute
  '/realtor': typeof RealtorRoute
  '/testimonials': typeof TestimonialsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/_authenticated/admin/listings': typeof AuthenticatedAdminListingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/loanofficer'
    | '/newartofliving'
    | '/realtor'
    | '/testimonials'
    | '/listings/$id'
    | '/admin/listings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/loanofficer'
    | '/newartofliving'
    | '/realtor'
    | '/testimonials'
    | '/listings/$id'
    | '/admin/listings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/loanofficer'
    | '/newartofliving'
    | '/realtor'
    | '/testimonials'
    | '/listings/$id'
    | '/_authenticated/admin/listings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  LoanofficerRoute: typeof LoanofficerRoute
  NewartoflivingRoute: typeof NewartoflivingRoute
  RealtorRoute: typeof RealtorRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ListingsIdRoute: typeof ListingsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loanofficer': {
      id: '/loanofficer'
      path: '/loanofficer'
      fullPath: '/loanofficer'
      preLoaderRoute: typeof LoanofficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newartofliving': {
      id: '/newartofliving'
      path: '/newartofliving'
      fullPath: '/newartofliving'
      preLoaderRoute: typeof NewartoflivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realtor': {
      id: '/realtor'
      path: '/realtor'
      fullPath: '/realtor'
      preLoaderRoute: typeof RealtorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/listings': {
      id: '/_authenticated/admin/listings'
      path: '/admin/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AuthenticatedAdminListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminListingsRoute: typeof AuthenticatedAdminListingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminListingsRoute: AuthenticatedAdminListingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  LoanofficerRoute: LoanofficerRoute,
  NewartoflivingRoute: NewartoflivingRoute,
  RealtorRoute: RealtorRoute,
  TestimonialsRoute: TestimonialsRoute,
  ListingsIdRoute: ListingsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
